### ISSUE TITLE
Video using StageGL does not behave correctly

### ISSUE THREAD

**Issue by AleixLoHi** [CreateJS/EaselJS#1011]
When using StageGL, video (mp4) is requested to play using a Bitmap as defined (and working) for Stage.
Deppending on the setup, either passing the file path directly or via an HTML element, it fails to render giving a different error.

When passed directly it only gives a "wrong image data"
When using HTML: "Invalid image provided as source. Please ensure source is a correct DOM element."

Tested in Chrome (72.0.3626.96) 64 bits

We found a solution to this problem by adding a non GL canvas and rendering the video there but i would like to know if there are plans for solving this issue in the future.

**Comment by DavidHGillen** [comment]
We maybe should add a couple of notes about this. The technique you're using is the same  technique that 3D engines like Three.js use in order to display video in WebGL. WebGL does not like to display video content because video requires processing to uncompress it each frame, processing that isn't built into the WebGL pipeline. The only way we could add this feature would be to automate the exact solution you have right now.

Given the groundwork we've laid with cacheless filters we might have a model we could use to automate this process, but there's no plans to implement it currently sorry. If you didn't want to manually make your own Canvas you can put a display element on the StageGL and give it a regular cache. That mechanism would basically create and manage another canvas behind the scenes for you.

Glad your workaround is doing well, and as it's the best exact approach to take I'll close this for now.

**Comment by gskinner** [comment]
I haven't had a chance to really think it through, but I believe you may be able to use the VideoBuffer class to solve this issue (as well as seeking issues you'll also encounter).

https://createjs.com/docs/easeljs/classes/VideoBuffer.html

If you try this, please report back here to let us know if it worked, and we can update the documentation appropriately.

**Comment by gskinner** [comment]
I looked into this, and it looks like VideoBuffer currently will not work as a Bitmap source in StageGL (ex. `new Bitmap(myVideoBuffer)`). I just pushed an update to StageGL that will fix that.

In the meantime, you should still be able to use it with a bit of code to call `getImage` each tick. Something like:

```
myBitmap.on("tick", function() {
  this.image = myVideoBuffer.getImage();
})
```

**Comment by djipco** [comment]
Has this ever been fixed? The best I can get with `StageGL` is the first frame of the video. Here's the code I am using:

```javascript
let myVideo = document.createElement('video');
myVideo.src = "test.webm";
myVideo.autoplay = true;
myVideo.muted = true;
let myBuffer = new createjs.VideoBuffer(myVideo);
let myBitmap = new createjs.Bitmap(myBuffer);
this.stage.addChild(myBitmap);
myVideo.play();
myBitmap.on("tick", () => myBitmap.image = myBuffer.getImage());
```

When I use `Stage` instead of `StageGL`, it works fine. By the way, it also does not work without a `Buffer`. So, for instance, the code below works with `Stage` but not with `StageGL`:

```javascript
let myVideo = document.createElement('video');
myVideo.src = "test.webm";
myVideo.autoplay = true;
myVideo.muted = true;
let myBitmap = new createjs.Bitmap(myVideo);
this.stage.addChild(myBitmap);
myVideo.play();
```

I am using `easeljs-NEXT.js`.
