### ISSUE TITLE
Feature request: Photoshop blending mode support for Filters

### ISSUE THREAD

**Issue by seawise** [CreateJS/EaselJS#284]
Can you please implement Photoshop blending modes (multiply, darken, screen, etc) for Filters? If you check source of this page - http://media.chikuyonok.ru/canvas-blending/, blending mode formulae are very simple, the only problem that you need to multiply image pixels with pixels of canvas below it, how to do it within EaselJS framework?

**Comment by ttessman** [comment]
I know this is closed but it's been 3 year. Any update on blending modes?

**Comment by lannymcnie** [comment]
I believe more blend modes have been implemented in the canvas compositeOperation since this post. Modes such as overlay, multiply, darken, lighten, etc make this a non-issue.

* https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
* http://caniuse.com/#feat=canvas-blending

Cheers,

**Comment by ttessman** [comment]
I'm kinda new but how would that work in createJS if it's not for the whole canvas rather elements.

**Comment by lannymcnie** [comment]
You can set `compositeOperation` on any EaselJS DisplayObject.

```js
bmp = new createjs.Bitmap(src);
bmp.compositeOperation = "multiply";
```

Cheers.

**Comment by ttessman** [comment]
Thank you
