### ISSUE TITLE
Mask is crisp

### ISSUE THREAD

**Issue by mamzellejuu** [CreateJS/EaselJS#363]
Hi,

I would like to know if they is a manner to have no crips for Shape that I apply as Mask on DisplayIObject.

Same vector with and without mask properties:
- http://mamzelle.ca/bug/without_mask.jpg
- http://mamzelle.ca/bug/with_mask.jpg

Something that I missed ?

Thank you for your help

**Comment by SeanJD** [comment]
Sorry for resurrecting such an old thread but it's the only info I can seem to find on this!

Is there any workaround for this other than the compositeOperation and cache?

As far as I can tell that won't work nicely with an animated mask as the performance on mobile suffers because of the cache on each frame. I have an animation exported from Flash which plays back fine in easeljs but it's still aliased on Chrome. The above fix works for a static mask that doesn't move but drops to unplayable frame-rates on mobile if the mask has to animate.

Or is there another method for getting crisp output from flash timeline animations (with masks) which will render nicely on Chrome too?

Thanks for the help

**Comment by lannymcnie** [comment]
If you are just masking an image, another workaround is to use a bitmap fill on the shape you want to mask out.

Like this: http://lab.gskinner.com/magnifier

Otherwise, there aren't any "fixes" for the aliasing on masks in Chrome at the moment.

**Comment by SeanJD** [comment]
Thanks lannymcnie but no that's not what I need to do.

I'm using the CreateJS export animation tool for Adobe Flash/Animate: 
This recreates the timeline animation in a format which is supposed to play back in the canvas element as animated vector shapes. Unfortunately this doesn't work properly if the animation has a mask and needs to be compatible with the Chrome browser. Which is a shame because in my book that just means it can't export timeline animations with masks (well it can but with horrible aliasing effects around what are meant to be crisp vector shapes)

I'll have to export it as a spritesheet animation/s instead.

Thanks anyway

**Comment by SeanJD** [comment]
I did more searching and came across this:
https://stackoverflow.com/questions/28903006/how-swiffy-antialias-canvas/28909316#28909316

Apparently it's the technique used by swiffy and the composition method has anti-aliasing built in (on Chrome too). 

It doesn't need to cache which as far as I could tell was the operation slowing down the other method.

I've done some quick tests with the above and a standard cjs shape masking an image and animating and it performs at 60fps on my mobile and has sharp anti-aliased edges on chrome.

Could anyone give me any pointers on how to hack the cjs output from flash (myAnim.js) so it uses this method for the masking and updates on every frame? That's where I'm currently stuck (though almost certain it will work as it does with standard cjs shapes)

Thanks
