### ISSUE TITLE
getChildByName does not work on movicle from timeline.

### ISSUE THREAD

**Issue by aholla** [CreateJS/EaselJS#430]
I have a movieclip that was built in flash and exported. 

I then create a shape and add it to the movieclip. When I try to retrieve it via its name, i get a null.

```
var mytimlineClip = new lib.TimelineClip();

var underlineGfx = new createjs.Graphics();
underlineGfx.beginStroke( '#2D52CD' );
underlineGfx.moveTo( 0, 0 );
underlineGfx.lineTo( underlineWidth, 0 );

var underline = new createjs.Shape( underlineGfx );
underline.name = 'underline';
mytimlineClip.addChild( underline );

mytimlineClip.getChildByName( 'underline' );// return null
```

This used to work, this is from an old project, I updated the libraries and now it does not work.

Thanks.

**Comment by tjutasi** [comment]
This is not about getChildByName, the problem is the instance names not exported from Flash CC (or Animate CC), all name property = null, so getChildByName useless.
For example, if you have a room (MovieClip) with different furnitures (MovieClips) you can't identify which is which while you enumerate the room's children.
So this seems a bug in Flash CC export, object instances should keep their names.
