### ISSUE TITLE
WebGL does not wait for bitmap to load

### ISSUE THREAD

**Issue by catalinberta** [CreateJS/EaselJS#559]
When rendering an image that has been assigned as bitmap, WebGL needs some time before it recognizes the existence of the bitmap, take this example:

var stage = new createjs.SpriteStage('canvas_id', false, false);
var image = new createjs.Bitmap("img/sprite.png");
stage.addChild(image);
createjs.Ticker.addEventListener("tick", handleTick);

Here, it won't load the image and it will give this error:
WebGL: INVALID_VALUE: texImage2D: invalid image
.WebGLRenderingContext]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'

However, if I assign the bitmap one second earlier width: 
var image = new createjs.Bitmap("img/sprite.png");
and run the code again, it works just fine.

Am I supposed to ensure that the image is loaded when running the code? Makes sense if I would have to do that, but why give such an error? It should just render the blank image (that didn't have time to load) instead or throwing errors that there is no image. 
Assigning the bitmap with a valid path should make it clear that there is an image there, loaded or unloaded.

I already tried loading the image ahead with preloadjs, but it doesn't matter, it only works if I assign it as bitmap and wait for it to load as bitmap. Am I missing something? Is this normal behavior?

**Comment by gskinner** [comment]
I took a look at this and you are correct, at present, `SpriteStage` expects images to be fully loaded prior to being added to the display list. This is because it attempts to create the texture at the moment the `Bitmap` or `Sprite` is added to the stage.

I've put together a quick fix that I think will work, but it can definitely use some testing. You can check it out in this branch:
https://github.com/CreateJS/EaselJS/tree/WebGLBitmapLoadHandling

In the interim, preloading your images using PreloadJS will resolve this issue. See the Runners.html example if you need any help with that.
https://github.com/CreateJS/EaselJS/blob/WebGLBitmapLoadHandling/examples/WebGL/Runners.html

**Comment by gskinner** [comment]
Just for further clarification, here is the delta for the fix: https://github.com/CreateJS/EaselJS/commit/cec2828d8e5955aebf2dc1bfff1132ece04cfecd

**Comment by catalinberta** [comment]
Tested in most browsers, works like a charm! I'm gonna make this available through a repo, but I'm hoping it will be available in the latest version of EaselJS also. Thanks for the support!

**Comment by gskinner** [comment]
I just pushed another update to the branch that simplifies logic, and resolves potential issues with textures being displayed improperly on the first frame after they load. Please test, and I will merge this back into master if everything looks good.
https://github.com/CreateJS/EaselJS/tree/WebGLBitmapLoadHandling

**Comment by catalinberta** [comment]
Fantastic, I will return with feedback asap.

**Comment by catalinberta** [comment]
I've tested in most browsers + ran all of my samples with it, works like a charm!

**Comment by gskinner** [comment]
Merged and pushed.
