### ISSUE TITLE
[Request] Sprite Stroke

### ISSUE THREAD

**Issue by webcaetano** [CreateJS/EaselJS#612]
Hello everyone of CreateJS
Hope you guys doing ok.

I'm looking for some stroke for Sprite 

![Imgur](http://i.imgur.com/iLHCRcl.png) 

This example are in flash , i used the shadow filter
The same are not possible in EaselJS Sprite because the blur there's not a strength parameter.
I take a look at the code to change it myself.
But apparently this is the behavior of canvas shadow. 

Any ideas?

**Comment by lannymcnie** [comment]
There is no support for this in Canvas or EaselJS. A custom filter is your best bet - but I am not sure where I would start with that.

**Comment by webcaetano** [comment]
Canvas support text stroke, and geometric stroke. But not image stroke.

Some idea is take the bitmap and fill it using ColorFilter in the color of the stroke
```js
ColorFilter(0,0,0,1, 0,0,255,0) // blue
```
Example https://jsfiddle.net/Zp9N7/3/

Next we should create a couple of copy with some algorithm to spread to all corners, based on stroke size.

Top, Top Right, Right, Bottom Right, Bottom,  Bottom left, Left, Top Left.
And them add the original Bitmap in the middle without filter.

I will try this later.

**Comment by webcaetano** [comment]
https://jsfiddle.net/Zp9N7/4/ :sunglasses:

Sprite animation with stroke. 1px size.
Now i need to improve this code for stroke size algorithm. 
And export bmp for custom filter purpose.

**Comment by webcaetano** [comment]
Update with stroke size.

https://jsfiddle.net/Zp9N7/5/

**Comment by lannymcnie** [comment]
I did a quick sample using this approach:

1. Create the filtered image (from your sample)
2. Put it in a container, and cache the container
3. Move the sprite to each quadrant of a 3x3 grid (similar to what you did), but then apply it to the container's cache using `updateCache`, which just draws the updated contents on top without clearing it.
4. Un-cache the bitmap (to remove the filter), and then apply it at 0,0, so the un-filtered version is part of the outline image.
5. Create a sprite with the container's cache

It works fine, but because the sprites are created with the smallest area possible, it bleeds into the other frames. You can get around this by leaving some padding around each item. The sprite that we used was created by Zoë, which has a frame padding option.

Here is the updated sample:
https://jsfiddle.net/lannymcnie/Zp9N7/6/

**Comment by webcaetano** [comment]
Very well done @lannymcnie. I didn't know about the updateCache. it's very nice. 
I see the part of the issue on the frame.
I also noticed you use a different algorithm to draw the stroke. 
It produce a different stroke corners. More like "cubic", that's cool.

May i ask a question?
How do change the image in the sprite after create them?
For example let imagine we need to add a stroke effect when mouseOver.

How about we create a stroke filter to add to EaselJS project as a new feature?

**Comment by lannymcnie** [comment]
I would probably use two Sprites instead of changing the image.

Yes, it is definitely not as accurate, but much faster, and for strokes less than 4px, it will not be very noticeable.

**Comment by webcaetano** [comment]
Yes, i saw that. until 4~6px is fine.
I do also think so that create a JavaScript function to show/hide between 2 sprites will be easy.

But there's a way to change the image after create the sprite?

I have tried to figure this out in so many ways but unsuccessful

**Comment by webcaetano** [comment]
Get it https://jsfiddle.net/webcaetano/Zp9N7/8/
