### ISSUE TITLE
Obfuscate Sprites EaselJS

### ISSUE THREAD

**Issue by webcaetano** [CreateJS/EaselJS#618]
**Is there any way to protect your sprites on EaselJS?**
Currently is too easy to download the sprites. 

On chrome just go to console -> resources [like this](http://i.imgur.com/3ArZN2k.png)

I made a resarch before i made this answer and found [this topic](http://stackoverflow.com/questions/20973528/canvas-disable-image-download?answertab=active#tab-top) . 
That could be very nice. Also we don't need to save the slices in a json like he said, if we have a [shuffle seed](https://github.com/webcaetano/SeededShuffle).

But, i didn't find any thing in nodejs(back-end) to make this image shuffle. 

I tried Node [GM](https://github.com/aheckmann/gm) but its looks too complicaded to bind a image on top of another with (w,h,x,y,offsetX,offsetY) 

I know always will have a way to "hack" the resource. But at least offer some difficult. 
Any ideas?

**Comment by lannymcnie** [comment]
You could certainly write a routine like the one you linked to above, but there is no direct support in EaselJS for this. Additionally you would need to create a tool to obfuscate the image, and create the JSON instructions. Definitely not something the core library would ever include.

Closing this because it is not a bug or issue with EaselJS.

**Comment by webcaetano** [comment]
Ok. Thanks.
