### ISSUE TITLE
createjs.proxy "is not a function" when stage doesn't contain any Bitmap object

### ISSUE THREAD

**Issue by ylazy** [CreateJS/EaselJS#665]
when the movie does not contain any Bitmap object, an error occurred: "createjs.proxy is not a function"

Please download the file bellow to reproduce the problem (Flash CC Canvas Document):
https://drive.google.com/file/d/0BxSLUkSih9Q_RXAtcGd0ZHhsNzQ/view?usp=sharing

**Comment by lannymcnie** [comment]
This isn't really a createjs bug. The proxy method only exists in PreloadJS, and is not used anywhere in the other libraries, nor is it used by the Flash export. 

In your frame script, you have used the proxy method, thereby putting in a dependency on PreloadJS, which is only used when images need to be preloaded.

Since you are trying to maintain scope, you can probably just use `Function.prototype.bind`, which is supported in all modern browsers (iOS5 and below are the only offenders that used to be an issue).

    this.interval = setInterval(replay.bind(this), 3000);

Earlier versions of PreloadJS supported IE6, 7, and 8, which is why there is a proxy function included in the the library. We cut of support for those browsers when we moved to PreloadJS 0.6.0. We will probably deprecate the proxy method in favor of `bind()` in the future.

Cheers.
