### ISSUE TITLE
Need something similiar to scrollRect

### ISSUE THREAD

**Issue by ylazy** [CreateJS/EaselJS#669]
Hi!
I'm building an Component library extending CreateJS. I'm having an issue with the scroller. I can't find something similiar to scrollRect or mask on Flash. Any idea?

Thanks!
Ylazy

**Comment by lannymcnie** [comment]
There is a mask property on any DisplayObject, which expects a Shape instance. The Flash CC export supports layer masks, which are converted to Shape masks. 
http://createjs.com/docs/easeljs/classes/DisplayObject.html#property_mask

**Comment by ylazy** [comment]
Sorry for delayed reply.
I tried but no luck. I need a way to create a clipping mask for display object and able to change position/resize it at run-time.

(lib.mask = function() {
	this.initialize();

	// msk (mask)
	var mask = new cjs.Shape();
	mask._off = true; // I can't find any doc about the _off property
	mask.graphics.p("AK8K8IOEAAIAAOEIuEAAg");
	mask.setTransform(160,160); // it's not match the transformation x and y of the movie clip mask that I created. The actual values is (230, 230). Then how to result these values? (160, 160)

	// main
	this.main = new lib.Symbol1();
	this.main.setTransform(100,100);

	this.main.mask = mask;

	this.addChild(this.main);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(505,430,70,70); // I have no idea with these value. How to result these value?

The original fla: https://drive.google.com/file/d/0BxSLUkSih9Q_ZjF4a1d0SDlHQjg/view?usp=sharing
Please help! It seems to be the hardest part of createjs for me :(

**Comment by lannymcnie** [comment]
If you plan on modifying the mask via code, it is advisable to create it and assign it to your `main` instance yourself. This means it is the size and position you expect, so it will scale as expected too. Note that masks are treated as siblings of the target that they apply to, so you will have to position it accordingly.

```js
var mask = new cjs.Shape();
mask.graphics.drawRect(0,0,90,90);
exportRoot.main.mask = mask;
```

If you want to use the mask from Flash, you will get a little more predictable results if you break it apart. Because it is a symbol, the Flash export does some funky things with it to apply it as a mask. If you break it apart so its just shape data, then it will make a little more sense.

To answer some of your points:
1. The _off property is for TweenJS to properly show and hide elements in a timeline tween. You don't have to worry about it.
2. The nominal bounds are the measured size of the contents in pixels. I believe the mask is not counted, but the size will be inclusive of any part that is masked.
3. The 160x160 position is a result of the mask shape being counter-transformed inside of its bounds. Ultimately it adds up to the 230x230. Again, Flash has some odd logic for positioning the coordinates, and we don't have any control. Happy to pass on this issue to them though.

Hope that helps.

**Comment by ylazy** [comment]
Thank much lanny. That really helped!
