### ISSUE TITLE
not supported sprite json format

### ISSUE THREAD

**Issue by viyancs** [CreateJS/EaselJS#689]
What should I do if I want to custom from another json format not like easejs json format.
here example sprite json format from another generator.
[player.txt](https://github.com/CreateJS/EaselJS/files/32680/player.txt)

**Comment by lannymcnie** [comment]
You will have to write a convertor. What software exports this format? Perhaps you could suggest to the software creator that they should support EaselJS as an export target.

**Comment by MannyC** [comment]
Looks like Spriter?  In any case, it looks look skeletal animation rather than a spritesheet.  So other than finding somebody else who has implemented an easeljs adapter for it, or writing your own, you could also have also have Spriter export it as PNGs and then use TexterPacker (or whatever) to create a single spritesheet along with EaselJS json (assuming Spriter won't pack the spritesheet for you itself, I haven't used it)

**Comment by viyancs** [comment]
@MannyC right i use spriter, is will be little difficult if I must create converter to do it.
is there any another similar spriter that was supported to generate sprite for easejs ?

**Comment by MannyC** [comment]
You'll find some work on adapters for Spine.  Probably because it has an official javascript runtime ( not sure if Spriter does).  Otherwise, as I said, exporting the animated spritesheets rather than the bone instructions might be what you want.

**Comment by lannymcnie** [comment]
Closing for now, since the solution is not applicable to EaselJS.
