### ISSUE TITLE
addedToStage and removedFromStage Event

### ISSUE THREAD

**Issue by chriswaldron15** [CreateJS/EaselJS#700]
Would it be possible to have an "addedToStage" event on display objects?

The use case for this came from a rendering system I developed using createjs which works on a per-component basis to control stage rendering, so the components on a stage request to be rendered/ request constant update on a stage and then request the stage stop rendering when it's done.

The issue is that my StageComponent.enableStageRendering class requires that the class be added to the stage before that happens. Often I want to start a tween or something on a component before it has been added to a stage instead of some class constructing my scene and then calling some init method on each component once it has been added to the relevant stage.

Or perhaps I'm being lazy ;) I feel it would be quite easy to fire an "addedToStage" event given that a reference to the DisplayObject's stage is assigned when a the display object is added to the stage.

As a side thing, I'm aware that Stage derived DisplayObject, which would make the event redundant on that class.

**Comment by lannymcnie** [comment]
This would be a fairly costly event, since every child would have to check their parent when the display list changes. 

This is possible using the `added` event, and then looking at the `stage` property (which is a getter that calls the internal `getStage()` method. If you do this for the cases you need, it will not have a huge performance hit.

Here is a sample approach:
```js
function checkOnStage(child) {
    var onStage = child.stage;
    if (!child._wasOnStage && onStage) {
         child._wasOnStage = true;
         child.dispatchEvent("addedToStage");   
    } else if (this.wasOnStage && !onStage) {
        child._wasOnStage = false;
        child.dispatchEvent("removedFromStage");
    }
}

// Run the method if the child is added or removed.
// Probably easier to call the method directly when you add/remove the children.
child.on("added", function(event) {
    checkOnStage(this);
});
child.on("removed", function(event) {
    checkOnStage(this);
});
````
You will also need to run the `checkOnStage` method when any containers that hold the child in question are added/removed.

As you can see, this could be a fairly costly operation to run on every child in a tree when anything on the stage changes.

I am going to close this issue for now. Feel free to continue discussion.

**Comment by chriswaldron15** [comment]
Thanks @lannymcnie, fair point I can see why it would be costly as every child (and children of children...) would have to update.

My assumption was that perhaps when a display object was added to a stage that it and all children would have their stage property set to the stage they were added to. So e.g. (this is very pseudo/ rough):

    p.addChild = function(child) {
        // ...current method
        if (this instanceof createjs.Stage) {
            child.setStage(this);
        }
    }

    p.setStage = function(stage) {
        if (stage == this.stage) {
            return;
        }

        if (this.stage) {
            this.dispatchEvent("removedfromstage");
        }

        this.stage = stage;
        this.dispatchEvent("addedtotage");

        for (var i in this.children) {
            this.children.setStage(stage);
        }
    }

I'm sensing just from writing that out that each child dispatching an addedtostage event would be costly and there is a reason the stage property is a getter so you only retrieve the stage when needed?

**Comment by gskinner** [comment]
Correct. This is definitely doable, but has a significant cost in performance. It just hasn't been worth that trade off, despite the fact that I would love to have the event (our work on the Flash components was actually the reason these events exist in AS3, so I'm intimately familiar with their value.

There are two costs: actually evaluating when an event should fire, and dispatching the event (ex. if you were to remove a tabbed view Container from the stage, then every single DisplayObject in all of its views, controls, etc would all need to dispatch a removed event). Our optimizations to "simple" (string based) event dispatching would help a lot (since no event is generated), but it's still a notable cost.

You could take a couple of approaches to this:

1. inject it via prototype - probably the most efficient but also potentially fragile.
2. use a factory to instantiate all of your DisplayObject instances, and add listeners for `added` and `removed`, you could then have the listeners evaluate and propagate the "addedToStage" and `removedFromStage` events as appropriate.

**Comment by chriswaldron15** [comment]
Given the performance implications (especially as we're producing content for mobiles) it's a very small sacrifice to us to be aware that calling `enableRendering` for our components can only be done once it is on a stage. So I fully understand the reasons that this event is not an attractive candidate for DisplayObjects.

Thanks for your swift responses and keep up the good work!
