### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by createbyte** [CreateJS/EaselJS#723]
Hi,

I'm currently developing a simple game. You can check it out here : http://insurancelovers.com/goa/africa/
Everything is working fine but the main issue is the performance. The game doesn't run smooth and is laggy. The performance in firefox is some what better as compared to chrome.
Any tips on improving the game performance?

Thanks

**Comment by MannyC** [comment]
Which bits aren't smooth for you?

**Comment by createbyte** [comment]
In particular the rollover functionality. The each individual map of the country should light up as soon as the cursor roll over it but it takes a few seconds before it lights up.

**Comment by createbyte** [comment]
And then on clicking I'm highlighting the maps using different colors which I have employed using the ColorFilter

**Comment by gskinner** [comment]
Hi @createbyte - as a friendly note, this Issues tracker is for logging reproducible bugs with the library. For more nebulous problems (like non-specific performance help), I'd strongly encourage you to use Stack Overflow. You'll get better / faster answers, and it keeps this tracker focused.

That said, it sounds like you are applying a filter on rollover. Depending on the area it is applied to, filters can be very expensive, so you might be seeing a delay in updates due to that. I'd recommend something other than a filter as your hoverstate if you think you can make it work. The fact that FireFox is faster is also a clue that this is the problem (Chrome usually performs better in canvas tasks, but filters are almost pure computation).

**Comment by MannyC** [comment]
I'd also suggest using `createjs.Ticker.timingMode = createjs.Ticker.RAF` instead of `createjs.Ticker.setInterval`

**Comment by MannyC** [comment]
Oh, and don't tick the stage unless it needs to be updated.
