### ISSUE TITLE
Does CreateJS has hitTest ?

### ISSUE THREAD

**Issue by hanzichi** [CreateJS/EaselJS#724]
I love createjs quite a lot ! But when I make a game, hit test is necessary. So I wonder if createjs has hit test module. I search a lot but I failed. Could someone help me ? Thanks in advance !

**Comment by danzen** [comment]
http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#method_hitTest - but watch, you may need to convert the point to local coordinates...  it does work.

**Comment by hanzichi** [comment]
thanks for your answer.

In fact, I have seen that, it seems we can check a point if it's in a rect or something else. I wonder if there are two sprites, how can I check if they have hitted ? What's more, hit from left, right, down or up? can I ? with great thanks !

**Comment by lannymcnie** [comment]
EaselJS has point-based hit detection ([tutorial](http://www.createjs.com/tutorials/HitTest/)). You can find out if a point intersects with visible pixels in an object. Box or circle collision is not built-in, so you can either write it yourself, or plug in any physics or collision library you like. For example, there is a Box2D demo in GitHub: http://sandbox.createjs.com/EaselJS_Box2dWeb/ ([source]( https://github.com/CreateJS/sandbox/tree/master/EaselJS_Box2dWeb))

I am closing this issue, since this forum is for reporting problems with the libraries, and not for general help. I recommend http://StackOverflow.com for future questions.

Cheers,
