### ISSUE TITLE
how to set winding rules in EaselJS

### ISSUE THREAD

**Issue by Mr-ziqiang** [CreateJS/EaselJS#725]
I cann't set the winding rules in EaselJS.
![1](https://cloud.githubusercontent.com/assets/16486126/12811934/8b6be09c-cb6a-11e5-8844-e4331d758c56.jpg)

this under is the source
![2](https://cloud.githubusercontent.com/assets/16486126/12811958/b559856c-cb6a-11e5-84a9-2f19c5f37d8e.jpg)

**Comment by lannymcnie** [comment]
Can you share a source file? How are you building this?

**Comment by MannyC** [comment]
Looks like easel will always just call `ctx.fill()` as per [graphics.js](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fill) but he's looking to use even-odd winding: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fill

**Comment by lannymcnie** [comment]
From my tests, paths will wind depending on the circular direction that you draw them. So drawing the outside shape in a clockwise pattern, and the inside shapes using a counter-clockwise pattern.

Here is an example I made using [Raw Canvas APIs](https://jsfiddle.net/lannymcnie/u0meqq9e/1/), and the same in [EaselJS](https://jsfiddle.net/lannymcnie/36496779/1/).

I threw together a graphic using Flash Pro export. It's not easy to tell what is going on due to the complex paths and coordinates, but you can see that there are 3 shapes, the second two cut out the first one.
* [Screenshot of image](http://screens.gskinner.com/lanny/Screen%20Shot%202016-02-04%20at%209.28.38%20AM.png)
* [Screenshot of code](http://screens.gskinner.com/lanny/Screen%20Shot%202016-02-04%20at%209.29.21%20AM.png)
* [Fiddle with isolated code](http://jsfiddle.net/lannymcnie/3pgmdznr/)
* [Flash Source files](https://github.com/CreateJS/EaselJS/files/117777/Winding.zip)

Hope that provides some insight.

**Comment by Mr-ziqiang** [comment]
hi,iannymcnie
this is the code,
js code:[https://jsfiddle.net/mr_ziqiang/23Lfam9d/1/](https://jsfiddle.net/mr_ziqiang/23Lfam9d/1/)
           [ http://game.iflashigame.com/hz.html]( http://game.iflashigame.com/hz.html)
as code:[http://game.iflashigame.com/Main.as](http://game.iflashigame.com/Main.as)

All the vector data is generate from potrace (http://potrace.sourceforge.net/potrace.html).
first , i convert the bitmap format to vector data(geojson format)
then, i get the data by ruby from geojson.

i write a as3 program ,it's ok.
but createjs not ok.
