### ISSUE TITLE
Error about cross-domain images

### ISSUE THREAD

**Issue by frops** [CreateJS/EaselJS#726]
Uncaught An error has occurred. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.

**Comment by lannymcnie** [comment]
This is not an issue with the library. Images can not be loaded locally or cross-domain, and then have their pixels accessed. EaselJS uses pixel-access to determine mouse interaction. You can:
1. Add a crossOrigin flag to your image, and make sure the server sends a allow-access header
2. If you are loading locally, run a local server like MAMP
3. Make sure all images are on the same domain
4. Add a rectangle hitArea to your images.

I am closing this, since it is not an issue with the library. If you have specific questions about how to solve a problem, I recommend StackOverflow. 

Cheers!
