### ISSUE TITLE
Mouse Events

### ISSUE THREAD

**Issue by 0xNacho** [CreateJS/EaselJS#727]
I'm going to start using EaseIJS in several projects and I need to clear up something: How does it handle mouse events?

As you know, canvas is just a bitmap that does not recognize shapes.

Does EaseIJS mantain a data structure (like quadtree) in order to keep a mapping between canvas coordinates and data values?

I'm not able to find the source code that implements this feature.

**Comment by lannymcnie** [comment]
EaselJS retains the DisplayList as DisplayObjects, which are drawn to the stage any time the stage is updated. The mouse events are handled by checking pixel opacity on an off-screen 1x1px canvas to determine when items are under the mouse. This provides pixel-perfect hit-detection. EaselJS supports DOM level 3 events, which supports bubbling, propagation, etc. You can subscribe to [events](http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#event_added) on any displayobject on the stage.

Here is the method in the source that does the hit detection. The stage handles mouse and touch events, but you can also trigger it manually with any point: https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/display/DisplayObject.js#L1050

Here is the documentation: http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#method_hitTest

Rollover hit detection must be turned on using `stage.enableMouseOver()`, which adds a check interval, since hit detection *can* be expensive. 
```js
stage.enableMouseOver(10); // 10 checks per second
```

You can also make objects [ignore the mouse](http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#property_mouseEnabled) (`mouseEnabled`) or determine how containers handle [mouse interaction of their sub-content](http://www.createjs.com/docs/easeljs/classes/Container.html#property_mouseChildren) (`mouseChildren`).

Hope that answers your question.

Note that this forum is for reporting issues. I recommend posting discussion on [reddit](http://reddit.com/r/createjs) and questions on [StackOverflow](http://stackoverflow.com).

Cheers,
