### ISSUE TITLE
the setStrokeStyle method have a problem.

### ISSUE THREAD

**Issue by Mr-ziqiang** [CreateJS/EaselJS#734]
in setStrokeStyle() when i set the param to 0.3,the alpha of border be changed and the thickness not be set to 0.3

`var shape=new createjs.Shape();
shape.x=100;
shape.y=100;
shape.graphics.setStrokeStyle(1).beginStroke("#ff0000");
shape.graphics.drawRect(0,0,50,50);
shape.graphics.setStrokeStyle(0.3).beginStroke("#ff0000");
shape.graphics.drawRect(60,0,50,50);
stage.addChild(shape);
stage.update();`

![11111](https://cloud.githubusercontent.com/assets/16486126/13066977/6e9ac15a-d4a6-11e5-8f4e-121985835af5.jpg)

**Comment by gskinner** [comment]
This is how the canvas deals with subpixel line widths. It cannot draw them any thinner than one pixel, so it alphas them out instead.

Note that you're seeing it as a fuzzy two pixel line because of a quirk of canvas where it considers a whole pixel coordinate to be between screen pixels, so it draws the lines on each side of the coordinate. Positioning lines on half pixels fixes this `graphics.moveTo(100.5, 0).lineTo(100.5, 100);

**Comment by Mr-ziqiang** [comment]
thanks,i set the value added 0.5 ,it's ok!
