### ISSUE TITLE
Performance Issue - MouseChildren = false

### ISSUE THREAD

**Issue by Anouck** [CreateJS/EaselJS#771]
Hello,

I have some performance Issue when using mouseChildren = false. After taking a look at how it works. I saw in https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/display/Container.js line 604 to 606.

```
if (!hitArea && child instanceof Container) {
	var result = child._getObjectsUnderPoint(x, y, arr, mouse, activeListener, currentDepth+1);
	if (!arr && result) { return (mouse && !this.mouseChildren) ? this : result; }
} 
```

My children under the Container with mouseChildren set to false have more than 200 children themselves.
Why do that :  child._getObjectsUnderPoint to not use it after?

I suggest this 
```
if (!hitArea && child instanceof Container) {
        if(mouse && !this.mouseChildren) return this;
	var result = child._getObjectsUnderPoint(x, y, arr, mouse, activeListener, currentDepth+1);
	if (!arr && result) { return  result; }
} 
```

Woudln't it be equivalent? Or there's something I've missed?

Thanks!

**Comment by gskinner** [comment]
Setting `mouseChildren` to false effectively retargets the mouse events on the children to the parent. It still needs to test the children for a "hit" in order to generate the event on the parent. If you simply want to disable all mouse events for the parent and children, then set `mouseEnabled` to false.
