### ISSUE TITLE
Firefox Problem with evt.nativeEvent.x

### ISSUE THREAD

**Issue by pastorpixel** [CreateJS/EaselJS#816]
When I use evt.nativeEvent.x I will get in Firefox an undefined. Here is the code for dragDrop Movieclip

this.green_mc.addEventListener("pressmove", dragMe.bind(this));
function dragMe(evt)
{
evt.currentTarget.x = evt.nativeEvent.x;
evt.currentTarget.y = evt.nativeEvent.y;
}
[changedVersion.zip](https://github.com/CreateJS/EaselJS/files/577581/changedVersion.zip)

When I use evt.stageX I will get a distance between the mouse position and the Movieclip, which is getting wider. You can download an example here
[stageXpressmove.zip](https://github.com/CreateJS/EaselJS/files/577590/stageXpressmove.zip)

I used evt.nativeEvent.clientX instead and that works good. But there is no documentation about it.

**Comment by lannymcnie** [comment]
The nativeEvent comes from the browser. You can read the documentation here: https://developer.mozilla.org/en/docs/Web/API/MouseEvent

Specifically, there is no `x` property in FireFox. You can view the browser support here: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/x

The issue you reported with `evt.stageX` is a known issue #772, where CSS transformations are not calculated by EaselJS. I don't know if you are the same person who reported [this today](http://stackoverflow.com/questions/40490701/drag-drop-not-working-properly-on-retina-ipad-createjs), but it is the same problem, where Adobe Animate CC export is doing CSS transforms on the stage, which will cause this issue. I have logged a bug to track this issue: #817.

I am closing this, since you first bug is a browser issue, and the second is a duplicate.

**Comment by lannymcnie** [comment]
Sorry, I spoke too soon.

The second problem you discuss (the "growing" distance) is just an issue with how you calculate the position. If you use `evt.stageX`, you get the stage's mouse coordinate -- however when the stage is made to be responsive, the content is scaled.

You can solve your issue by using the clip's coordinates inside its parent instead of the stageX/Y:

```js
function dragMe(evt)
{
    var p = this.globalToLocal(evt.stageX, evt.stageY);
    evt.currentTarget.x = p.x;
    evt.currentTarget.y = p.y;
}
```

**Comment by pastorpixel** [comment]
Thanks a lot
