### ISSUE TITLE
how to extend class from animate?

### ISSUE THREAD

**Issue by amihanya** [CreateJS/EaselJS#838]
I have a FLA file that export to canvas, I add a linkage movieClip that call OpenScreen_mc.
i try to extend the OpenScreen_mc
i try this code:

```js
(function (window) {
  function OpenScreen() {
     // this.Container_constructor();
  }
  var p = createjs.extend(OpenScreen, lib.OpenScreen_mc);
  window.OpenScreen = createjs.promote(OpenScreen, "lib.OpenScreen_mc");
}(window));
```
 
and call to the "class" like this:
```js
var  openScreen_mc = new OpenScreen()
stage.addChild(openScreen_mc);
```
 
but i don't see the OpenScreen on the stage.
i try to call the this.Container_constructor(); but i get overFlow.
How can i extend it?

**Comment by lannymcnie** [comment]
Sorry for the late (probably unhelpful) reply.

You should be able to extend the class. There is an error in your extend, the 2nd parameter of "promote" is just the common name you want to prepend to methods.

```
window.OpenScreen = createjs.promote(OpenScreen, "OpenScreen_mc");
```

Not sure if that helps. I am closing the issue due to its age. Feel free to reopen if the issue persists or you have more info.
