### ISSUE TITLE
Custom property added to Event object - Missing after first dispatch?

### ISSUE THREAD

**Issue by seanyoncraic** [CreateJS/EaselJS#845]
When you add a custom property to an Event object such as:
```
var hitEvent = new createjs.Event("gameEvent", true);
hitEvent.id = "playerHit";
```
And dispatch as normal (sprite is a sprite object on displaylist):
`sprite.dispatchEvent(hitEvent);`

The first time the event is detected by a listener, its handler can access the id property via the received event object. But the properties are missing the second time the same event object is dispatched and received by the event handler.

This fixes it if done before any dispatch:
`hitEvent.target = null;`

This issue did not exist in EaselJS version 0.7

Any ideas?

**Comment by lannymcnie** [comment]
To prevent race conditions, or other issues that could _potenially_ occur when reusing events, event objects that already have a target (and have therefore been dispatched) will be cloned before dispatching (and therefore omit any custom properties). Wiping out the `target` causes the event to be treated as a new event, which changes the behaviour.

This is unlikely to change, as it addresses issues that are typically difficult to debug, and was built this way by design.

A simple fix is to either make new events each time, make a custom event class that clones the properties you need. Check out the [ProgressEvent class](http://createjs.com/docs/preloadjs/files/preloadjs_events_ProgressEvent.js.html#l41) which does this, or keep using your workaround.

Cheers.
