### ISSUE TITLE
StageGL: BitmapText Doesn't Call _updateText() on Redraw

### ISSUE THREAD

**Issue by Cleod9** [CreateJS/EaselJS#851]
So my `BitmapText` wasn't rendering and I learned that **for StageGL canvases the text is never redrawn because `_updateText()` is never called**

For 2D canvases `_updateText()` is called whenever `draw()` is called, but StageGL doesn't use `draw()` so the text is never updated.

During my debug process I also noticed this which gave me a bit of a scare:

https://github.com/CreateJS/EaselJS/blob/5d1d5a2f7dc7a1af963fec9770e474a675c2b060/src/easeljs/display/StageGL.js#L2412

It seems like it might be a lot safer in the long run to enum-ify the `_webGLRenderStyle` property of each class's prototype. I spent a good 5 hours thinking that's where the problem was only to find out otherwise. There is also not much benefit in looping through an array of classes here in general.

Also btw do you guys have a home for active development discussion like Slack or a discussion board? I know there's a Reddit, Google+, and Twitter but those places seem more appropriate for generic things like questions/announcements, etc. I'm interested in contributing and following along with future developments :)

**Comment by DavidHGillen** [comment]
![image](https://cloud.githubusercontent.com/assets/932765/24311437/c17b85fa-1099-11e7-946a-7cf246da4c75.png)

Here's the callstack by which that function is intended to get called. You might be missing it if you're simply calling "draw" instead of "update", I'll make sure that gets put into the BitmapText documentation.

As for why:
There was a minor change to BitmapText. We used to trigger it's update text inside of the scene-graph walk. As StageGL had it's own way of walking the scene-graph (for optimizations sake) we would either need a special case for only BitmapText (not awesome) or to build in a API by which any DisplayObject could be warned to do a "update". Like an event that it was about to be drawn, so rather than re-invent the wheel I tied it into the existing draw start/end events. This was the same way we're doing the DOMObject, so more consistency and a win all-around. These event listeners are added during the private _tick function, which is again only engaged if you call update rather than draw.

So everything should work smoothly if you're calling update, which should be what most of our demos show. If it isn't or you've got some ideas feel free to get back to us. I'll get the documentation fixed so others don't have the same mystery.

**Comment by DavidHGillen** [comment]
Also re: enumifying the types, that would definitely be a good approach and one I've considered, as you can see there's a comment just above the code showing we're actively considering other alternatives. But there's a few questions internally we haven't decide on answers for to pick the best approach, like how many draw types are there probably ever going to be. When adjusting something that's going to get processed for every object it can have quite the speed impact when you process as many objects as StageGL is intended to, so I don't want to make any poor choices.

**Comment by Cleod9** [comment]
@DavidHGillen Thanks for the response, I looked into what you said and it turns out that the reason I wasn't seeing updates was because we set `tickEnabled` to false globally for performance reasons. And of course since `_updateText()` is tied to those draw event listeners that explains why it didn't work with the new StageGL. Another note for the docs I suppose!

Also take your time with the enums thing, it was merely a suggestion. Though I don't think you can really go wrong here as long as you keep those values internal to the library. Since there are so few display classes to be concerned with, a good start would probably be to remove that forEach loop in favor of clearly stating what the integers represent in the form of a comment until you decide what to do with it

**Comment by lannymcnie** [comment]
Closing this, since its not longer relevant with the latest changes. Feel free to reopen if there are still related issues.
