### ISSUE TITLE
BlurFilter doesn't use shader program on StageGL

### ISSUE THREAD

**Issue by ricofegh** [CreateJS/EaselJS#866]
I'm doing something like this with StageGL:

var bmp = new createjs.Bitmap(img);
bmp.filters = [new createjs.BlurFilter(10, 10, 1)];
bmp.cache(0, 0, 100, 100);
container.addChild(bmp);

I tried to comment out FRAG_SHADER_BODY and _applyFilter body one after another inside BlurFilter code and found that logic in _applyFilter is still in use, while shader is not.

Is there any way to apply BlurFilter to make it use shader?

**Comment by DavidHGillen** [comment]
You're using a Context2D cache, as the cache is Context2D so is the filter being applied. To use the WebGL filters you have to be using a WebGL cache. Change this line:

~bmp.cache(0, 0, 100, 100);~
`bmp.cache(0, 0, 100, 100, 1, {useGL: "stage"});`

The inline documentation goes over this, but you need to know to look. It's something we're planning on writing some more in depth articles about soon. Filters modify what's draw to to the cache not how the cache is displayed.

**Comment by ricofegh** [comment]
Actually I found the following line in Filters_GL-GL.html from examples:

`bmp.cache(0, 0, img.width, img.height, 1, "stage");`

which seems to be outdated.

However, when I changed "stage" to {useGL: "stage"} in this example it starts fall with the error: 
`TypeError: Cannot read property 'isWebGL' of null.`

**Comment by DavidHGillen** [comment]
I think you caught a couple of bugs there.

1) The Filters_GL-GL example should be using the new API it was changed relatively recently to be more flexible but it seems we missed the demo, not sure how we missed it but I'll get that fixed.

2) As for your error, that's because in order to use the "stage" command it makes the cache on the stage's context, but it doesn't know what stage because you haven't added it to a stage yet. That should not be breaking, we should be providing an error notification and recovering, apologies.

The best fix is to move your add child command before your cache command. There's the option to use "new", but I don't recommend that. It will have significantly worse performance compared to "stage" when your stage is already StageGL, "new" is best used when you main stage is Context2D.

**Comment by ricofegh** [comment]
Thank you, works perfect now
