### ISSUE TITLE
Bad libraries published for EasleJS

### ISSUE THREAD

**Issue by fabioelia** [CreateJS/EaselJS#869]
It looks like some old / strange merge has gotten in introducing old code.

We've started seeing strange behavior in our code over the last week stemming from easeljs.

It's easy to spot looking here:
https://github.com/CreateJS/EaselJS/blob/master/lib/easeljs-0.8.2.combined.js
Then viewing the commit it came in
https://github.com/CreateJS/EaselJS/commit/06a2c978212360e23d72dcd32c223102a32170a1
And seeing the PR that it was associated with
https://github.com/ValtoLibraries/EaselJS/pull/2

It seems to have introduced old code into the project. It's easy to spot the "MasterFilter" which has been removed 
https://github.com/CreateJS/EaselJS/blob/master/lib/easeljs-0.8.2.combined.js#L5927

Just a heads up, we ended up rolling back to #993834eeddf2d61b7639d2a0259ffcdbceb6aeaf

**Comment by lannymcnie** [comment]
Wow, thanks for the find!

A build was run and committed on our prototype StageGL branch by mistake some time ago (Feb 2016), which didn't affect anything, but was included in the StageGL merge we did recently, which is why it just showed up. 

I will revert the tagged 0.8.2 files in GitHub.

Cheers!

**Comment by lannymcnie** [comment]
I have reverted all the 0.8.2 tagged files. Thanks again!

Note that the CDN versions were unaffected.
