### ISSUE TITLE
Integrating with Backbonejs

### ISSUE THREAD

**Issue by yuvrajm** [CreateJS/EaselJS#876]
I wish to integrate Easel with backbone.js
I am stuck on the position of defining the view. Would appreciate if some one can direct me. How can we associate a view with the canvas.
My purpose of using Easel with backbone is purely for better code structure and easier flow.

**Comment by lannymcnie** [comment]
Can you be more specific?

One issue we have found with frameworks like Backbone, is you can not define a Stage with a string ID, since the canvas only exists in a document fragment, and not in the actual DOM.

```js
// Wrong
var stage = new createjs.Stage("canvasId");

// Right
var canvas = this.$("#canvasId");
var stage = new createjs.Stage(canvas);
```

You will have to determine how to do the canvas element look-up based on your setup.

If you have additional questions, please post to StackOverflow instead. This list is for reporting issues with the libraries.

Cheers,
