### ISSUE TITLE
Mouse events not working

### ISSUE THREAD

**Issue by rafid009** [CreateJS/EaselJS#880]
I am trying to make a collaborative drawing tool with HTML Canvas and EaselJS in my project. The back end is in spring-boot & hibernate and I am using thymeleaf to communicate with the front end. But my easelJS mouse events are not working at all.

**Comment by lannymcnie** [comment]
Sorry, you are going to have to provide more info than this.

I am closing this issue -- if you encounter an actual bug that is reproducible, then feel free to log it here. Otherwise I encourage you to create a demo of the issue, and ask specific questions on StackOverflow (where we are very active answering questions)

Cheers.
