### ISSUE TITLE
Draggers sticks to the mouse 

### ISSUE THREAD

**Issue by vkadri** [CreateJS/EaselJS#918]
1. Bring up this link -  http://www.createjs.com/demos/easeljs/draganddrop
2. Select a dragger and then drag off the side of the screen quickly

Actual: The dragger doesn't get moved all the way to the edge.
Expected: The dragger should be moved all the way to the edge.
[Recording #1.zip](https://github.com/CreateJS/EaselJS/files/1420405/Recording.1.zip)

**Comment by lannymcnie** [comment]
This is just because you are moving your mouse too fast outside the draggable area, and it is inside of an iframe on the CreateJS site (so the mouse events outside the iframe don't get passed in). If you check out the demo on its own, it works fine.
https://www.createjs.com/demos/easeljs/DragAndDrop.html

Cheers!
