### ISSUE TITLE
Is there a way to programmatically draw an outline around a bitmap?

### ISSUE THREAD

**Issue by KidHowren** [CreateJS/EaselJS#933]
I need to draw an outline around the edge of bitmaps that are complex shapes, meaning there are hundreds of coordinates needed to define the path. I tried using freehand draw to manually find what the coordinates would need to be but it's pretty sloppy, not to mention super tedious. I'm currently using PNGs though I know that SVGs contain coordinate path information already. Is there an easier way to do this kind of thing using easeljs, or am I stuck finding/drawing the coordinate path manully via the lineTo method? I attempted to figure out a way to do it using the mask filters but I couldn't get it to work right.

If no such technique exists, perhaps someone can help me convert the following code from html canvas api methods to the proper easeljs methods? This method works fine to get the outline to show, but I can't get it to play nicely with easelJS for some reason. I had to use updateCache('source-over') even though pretty much every other draw operation I'm using must be committed using updateCache() (no composite operation passed). The user has to be able to add/remove items to/from the container and the outlines are often times erased when regular display objects are added or vice versa. Obviously this must be because easeljs has no way of knowing about canvas operations that aren't being tracked as display objects. 

Here is the code I used to achieve that outline though, it's a technique I found online where you essentially clone the image, apply a filter using the color your want to outline with, then redraw the image several times using small offsets (which is probably costly to performance):

```
vm.offsetMap =  [-1, -1], [-0.505, -1], [0, -1], [0.505, -1], [1, -1], [-1, -0.505], [-0.505, -0.505], [0, -0.505], [0.505, -0.505], [1, -0.505], [-1, 0], [-1.25, 0], [-0.505, 0], [0.505, 0], [1, 0], [1.25, 0], [-1, 0.505], [-0.505, 0.505], [0, 0.505], [0.505, 0.505], [1, 0.505], [-1, 1], [-0.505, 1], [0, 1], [0.505, 1], [1, 1];

function addOutline(bitmap, container, color) {
     var canvas = container.cacheCanvas, ctx = canvas.getContext("2d");
     var t = 6, x = 15, y = 15; //outline thickness & origin point

     vm.offsetMap.forEach(function(offset) { ctx.drawImage(bitmap.image, x + offset[0] * t, y + offset[1] * t) });
     ctx.globalCompositeOperation = "source-in";
     ctx.fillStyle = color;
     ctx.fillRect(-15, -15, canvas.width, canvas.height);
     //Performs final redraw of original image without any offsets over the color-filled outlined-shape
     ctx.globalCompositeOperation = "source-over";
     ctx.drawImage(bitmap.image, 15, 15);
     container.updateCache('source-over');
}
```

Any advice or direction is greatly appreciated!

**Comment by BobarTrump** [comment]
I guess you want to do it for collision ? One simple solution I've found is using Tiled and its polygon tools then I export a JSON file that contains the coordinates I want. it's tricky because you need to handle correctly the center of your coordinates but once it's done, it works perfectly.  Anyway, I'm not sure it's on topic with EaselJS, you should probably ask on Stack Overflow about that if the question doesn't already exists

**Comment by lannymcnie** [comment]
What is the outline for? Could you use a Canvas Shadow/Glow to get the effect you are looking for? You would want to cache that as well, as Shadows are pretty slow in Canvas. Your filter/clone effect should be fine too, as long as you only do it once, and cache the result.

**Comment by mjonkman** [comment]
Why not create a secondary canvas (not the CreateJS stage canvas). Then create a shape and draw that canvas into the shape:

NOTE: I generally code in TypeScript so the way I created the canvas below might not be correct for standard JavaScript:

var myCanvas = document.createElement('canvas');
myCanvas.width = xx;
myCanvas.height = yy;

var ctx = myCanvas.getContext("2d");
// do your draw code into the canvas of your irregular bitmap and its outline.

then 
var myComplexShape = new createjs.Shape();
var g = myComplexShape .graphics;
g.beginBitmapFill(myCanvas, "no-repeat", null);
g.drawRect(0,0,myCanvas.width, myCanvas.height);
g.endFill();

you should be able to release "myCanvas" or keep it around and use it as the permanent canvas to render your irregular bitmaps to generate shapes from.

Now you have a Shape instance that contains your custom bitmap shape with its outline. You can add and remove the shape from the createjs.Stage at will and not have any issues. I don't know how createjs holds the bitmap fill in the shape but I do this quite frequently when I need to create an independant snapshot of a symbol that is already on the stage or portion of that symbol. Although my path is slightly different since its generally a vector shape to begin with and I just cache the neccessary portion of the symbol at the appropriate scale, use that as a bitmapFill and then uncache the symbol.
