### ISSUE TITLE
how to scale to NEAREST?

### ISSUE THREAD

**Issue by txiaocao** [CreateJS/EaselJS#940]
scale the Bitmap use
```js
bitmap.scaleX = 5
bitmap.scaleY = 5
```

like PIXI SCALE_MODES
http://pixijs.download/release/docs/PIXI.html#.SCALE_MODES

**Comment by DavidHGillen** [comment]
The scale modes are actually referring to the pixel interpolation of the drawing when drawn scaled. Your scale values aren't affected by this setting, just how it looks. Because Pixi is WebGL first and Context2D fallback they're able to expose WebGL properties directly and warn you not everything will work in fallback mode. As EaselJS tries to treat both as first class and give a similar API, when Context2D and WebGL don't line up it's tough to provide a simple answer, especially when people expect the GL properties :)

To give you a tldr;
for Stage: 
- Nearest (experimental): https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled
- Linear: Default
for StageGL:
- Nearest: Default
- Linear: "StageGL(canavs, {antialias: true});" and square power of two textures

Now for the long answer:
Context2D (Stage) by default uses linear interpolation on everything, and in fact the API to turn it off is considered experimental. Because it's a non standard experimental API, Stage is not going to implement a property for it. Otherwise we'd just receive a lot of bugs that are actually browser complaints. So there's going to be no API for it till it's standardized. One of the new filters we're writing internally is a pixelate filter though, and it could be used to create the nearest neighbor effect. Canvas 2D is flexible enough that you could reach in and grab the context and turn on the experimental tech if your target market supports it though.

WebGL 1.0 (StageGL) on the other hand has both a minification and a magnification setting and uses a nearest neighbour interpolation for each by default. WebGL 1.0 prefers square, power of two textures in order to perform both min and mag linear interpolation. When I say "prefers" there's some performance aberrations and inconsistent behaviour to watch out for. To make it reliable and simple we provide the following API. When making a new StageGL instance, provide the antialias flag: `new StageGL(canavs, {antialias: true});` this tells the stage to always try to smooth when it can. Then when providing any textures you wish to be smoothed, make sure they're square power of twos. Of course only square objects would be a pain, but it's just the texture source that has to be square, not the display object. Use `Bitmap.sourceRect`s or Sprites to have a non square object still. Sprites are always a good idea in GL due to reusing textures. WebGL 2.0 does away with the internal issues with linear interpolation but is still not prevalent enough for us to make significant API changes yet, so stay tuned for that later on.

Hope that answers the question and gets you going.

**Comment by txiaocao** [comment]
thanks~~
