### ISSUE TITLE
StageGL, AlphaMaskFilter not working on cached items with latest easeljs-NEXT  

### ISSUE THREAD

**Issue by Nestorferrando** [CreateJS/EaselJS#953]
With the latest release of easeljs-next library, AlphaMaskFilter does not seem to work anymore.

The result shown below is just applying a square shape as alphafilter to a movieclip. Of course, later I cache the movieclip bounds.

this worked fine on easel-js 1.0.0

![image](https://user-images.githubusercontent.com/4629402/39393076-fc361a04-4ac0-11e8-8c0b-94dd47e60220.png)

**Comment by DavidHGillen** [comment]
There were updates to the filter so it was specifically tested. Can you give me more details or a codepen to compare against my local version?

**Comment by Nestorferrando** [comment]
Hi again! I worked a litte more on this.

it looks that the behavior has changed a little bit, I'll explain a simple case:

for a cached text of size 200x50, if I add a filter of smaller size:

		 var box = new createjs.Shape();
		box.graphics.beginFill("red");
		box.graphics.drawRect(0, 0, 50, 20);
		box.cache(0, 0, 50, 20);
		
		closure$text.font = 'bold 32px Arial';
		closure$text.color = '#0000FF';
		closure$text.text = Math.round(createjs.Ticker.getMeasuredFPS()).toString() + ' fps';
		closure$text.filters = [new createjs.AlphaMaskFilter(box.cacheCanvas)];
		closure$text.cache(0, 0, 200, 50);

produce this result on 1.0.0:
![image](https://user-images.githubusercontent.com/4629402/39439943-94bbbe8e-4ca9-11e8-9c70-f8343240c852.png)

and this on latest build:
![image](https://user-images.githubusercontent.com/4629402/39439839-3e47e294-4ca9-11e8-87f2-e76c2c5f04d2.png)

if I set box cache size similar to text cache size everything works fine, it looks like in the latest release, there is some type of scaling the size of the filter cache to fit the target cache. I don't know this is actually the intended behavior or a bug

Find attached the source code with the case, the code is in production/sample/sample.js

[AlphaMaskFilter_problem.zip](https://github.com/CreateJS/EaselJS/files/1961500/AlphaMaskFilter_problem.zip)

**Comment by DavidHGillen** [comment]
There was a standardization of filter behavior, so this is expected.

Before depending upon whether you were using GL or one filter or another it was hit or miss exactly how the filter would handle images of differing sizes. So the general rule was implemented that all filter texture inputs would be scaled to match the cache, no if and or buts, both gl and regular. This more predictable behavior is better for everyone rather than trying to memorize and document the hit or miss way filters handled texture inputs before. If you need to transform an image being fed into a filter, using another cache to perform the transformation and then supplying that cache canvas as the image is the recommended workflow. We've discussed adding transformation controls for filter texture inputs but the API for it, and the technical complications of implementing full control in Context2D mean that if there's enough desire for it, the change is still on the horizon.

The inline documentation was updated to reflect this, but it's a super easy note to miss. Apologies for the confusion. :)

**Comment by Nestorferrando** [comment]
Thanks for clarify it, I close the issue then.
