### ISSUE TITLE
When applying a cacheless filter to a displayobject, elements behind it dissappear

### ISSUE THREAD

**Issue by Nestorferrando** [CreateJS/EaselJS#955]
Hi again

Sorry if I'm a bit annoying posting all the issues I found, but I'm quite interested in the new features you are adding to createjs. I hope that these posts help to ironing any remaining bugs.

I've been trying to tint a container to green with a cacheless color filter, and for some reason, the objects behind disappear.

with directDraw on (no cachaless filter):
![image](https://user-images.githubusercontent.com/4629402/39464066-b38d2f74-4d1b-11e8-8747-111104e36ae0.png)

with directDraw off (cachaless filter):
![image](https://user-images.githubusercontent.com/4629402/39464082-c3a91116-4d1b-11e8-978f-268b4fd4e500.png)

this is the code with the example (file production/sample/sample.js):

[text_colortint.zip](https://github.com/CreateJS/EaselJS/files/1963152/text_colortint.zip)

thanks

**Comment by DavidHGillen** [comment]
2 bugs going on here!

turns out I was resizing the texture used to preserve the elements rendered before the autocache so the resizing erased them. Fixed that
Then the color filter wasn't handling pre multiplied alpha correctly. Fixed that.

Sorry for the delay, they're live as of:
https://github.com/CreateJS/EaselJS/commit/deba09afbb221db245cf4bc56745f231c7b482f3

**Comment by Nestorferrando** [comment]
thanks!  I'll try it ASAP
